### ISSUE TITLE
Add `Deleted` status

### ISSUE THREAD

**Issue by hoanhan101** [vapor-ware/netbox-virtual-circuit-plugin#26]
Sometimes a customer might want to delete a Virtual Circuit but we don't want to delete it immediately in our database yet. What we can do instead is to mark it `Deleted` and manually delete it later.

**Comment by marcoceppi** [comment]
I think either `deleted` or `removed` as a status would work. Alternatively, since "deleted" is just having the record removed, we could move from `pending deletion` to `pending deactivation` and `deactivated` as statuses which might better represent what's happening same with `provisioning` / `de-provisioning` / `deprovisioned`
